import { Injectable } from "@angular/core";
import { Industry } from "src/_model/industry";

@Injectable({
  providedIn: "root"
})
export class IndustryService {
  industries: Industry[];

  constructor() {
    this.industries = [
      { name: "Accounting" },
      { name: "Airlines/Aviation" },
      { name: "Alternative Dispute Resolution" },
      { name: "Alternative Medicine" },
      { name: "Animation" },
      { name: "Apparel &amp; Fashion" },
      { name: "Architecture &amp; Planning" },
      { name: "Arts &amp; Crafts" },
      { name: "Automotive" },
      { name: "Aviation &amp; Aerospace" },
      { name: "Banking" },
      { name: "Biotechnology" },
      { name: "Broadcast Media" },
      { name: "Building Materials" },
      { name: "Business Supplies &amp; Equipment" },
      { name: "Capital Markets" },
      { name: "Chemicals" },
      { name: "Civic &amp; Social Organization" },
      { name: "Civil Engineering" },
      { name: "Commercial Real Estate" },
      { name: "Computer &amp; Network Security" },
      { name: "Computer Games" },
      { name: "Computer Hardware" },
      { name: "Computer Networking" },
      { name: "Computer Software" },
      { name: "Construction" },
      { name: "Consumer Electronics" },
      { name: "Consumer Goods" },
      { name: "Consumer Services" },
      { name: "Cosmetics" },
      { name: "Dairy" },
      { name: "Defense &amp; Space" },
      { name: "Design" },
      { name: "E-learning" },
      { name: "Education Management" },
      { name: "Electrical &amp; Electronic Manufacturing" },
      { name: "Entertainment" },
      { name: "Environmental Services" },
      { name: "Events Services" },
      { name: "Executive Office" },
      { name: "Facilities Services" },
      { name: "Farming" },
      { name: "Financial Services" },
      { name: "Fine Art" },
      { name: "Fishery" },
      { name: "Food &amp; Beverages" },
      { name: "Food Production" },
      { name: "Fundraising" },
      { name: "Furniture" },
      { name: "Gambling &amp; Casinos" },
      { name: "Glass, Ceramics &amp; Concrete" },
      { name: "Government Administration" },
      { name: "Government Relations" },
      { name: "Graphic Design" },
      { name: "Health, Wellness &amp; Fitness" },
      { name: "Higher Education" },
      { name: "Hospital &amp; Health Care" },
      { name: "Hospitality" },
      { name: "Human Resources" },
      { name: "Import &amp; Export" },
      { name: "Individual &amp; Family Services" },
      { name: "Industrial Automation" },
      { name: "Information Services" },
      { name: "Information Technology &amp; Services" },
      { name: "Insurance" },
      { name: "International Affairs" },
      { name: "International Trade &amp; Development" },
      { name: "Internet" },
      { name: "Investment Banking" },
      { name: "Investment Management" },
      { name: "Judiciary" },
      { name: "Law Enforcement" },
      { name: "Law Practice" },
      { name: "Legal Services" },
      { name: "Legislative Office" },
      { name: "Leisure, Travel &amp; Tourism" },
      { name: "Libraries" },
      { name: "Logistics &amp; Supply Chain" },
      { name: "Luxury Goods &amp; Jewelry" },
      { name: "Machinery" },
      { name: "Management Consulting" },
      { name: "Maritime" },
      { name: "Market Research" },
      { name: "Marketing &amp; Advertising" },
      { name: "Mechanical Or Industrial Engineering" },
      { name: "Media Production" },
      { name: "Medical Device" },
      { name: "Medical Practice" },
      { name: "Mental Health Care" },
      { name: "Military" },
      { name: "Mining &amp; Metals" },
      { name: "Motion Pictures &amp; Film" },
      { name: "Museums &amp; Institutions" },
      { name: "Music" },
      { name: "Nanotechnology" },
      { name: "Newspapers" },
      { name: "Non-profit Organization Management" },
      { name: "Oil &amp; Energy" },
      { name: "Online Media" },
      { name: "Outsourcing/Offshoring" },
      { name: "Package/Freight Delivery" },
      { name: "Packaging &amp; Containers" },
      { name: "Paper &amp; Forest Products" },
      { name: "Performing Arts" },
      { name: "Pharmaceuticals" },
      { name: "Philanthropy" },
      { name: "Photography" },
      { name: "Plastics" },
      { name: "Political Organization" },
      { name: "Primary/Secondary Education" },
      { name: "Printing" },
      { name: "Professional Training &amp; Coaching" },
      { name: "Program Development" },
      { name: "Public Policy" },
      { name: "Public Relations &amp; Communications" },
      { name: "Public Safety" },
      { name: "Publishing" },
      { name: "Railroad Manufacture" },
      { name: "Ranching" },
      { name: "Real Estate" },
      { name: "Recreational Facilities &amp; Services" },
      { name: "Religious Institutions" },
      { name: "Renewables &amp; Environment" },
      { name: "Research" },
      { name: "Restaurants" },
      { name: "Retail" },
      { name: "Security &amp; Investigations" },
      { name: "Semiconductors" },
      { name: "Shipbuilding" },
      { name: "Sporting Goods" },
      { name: "Sports" },
      { name: "Staffing &amp; Recruiting" },
      { name: "Supermarkets" },
      { name: "Telecommunications" },
      { name: "Textiles" },
      { name: "Think Tanks" },
      { name: "Tobacco" },
      { name: "Translation &amp; Localization" },
      { name: "Transportation/Trucking/Railroad" },
      { name: "Utilities" },
      { name: "Venture Capital &amp; Private Equity" },
      { name: "Veterinary" },
      { name: "Warehousing" },
      { name: "Wholesale" },
      { name: "Wine &amp; Spirits" },
      { name: "Wireless" },
      { name: "Writing &amp; Editing" }
    ];
  }

  getAll() {
    return this.industries;
  }
}
